### PR TITLE
Feature/feature redux setup

### PR DESCRIPTION
**Pull request by Bhuvneshwar-MB**
Implementation of Redux store and redux saga.

### CODE REVIEW

**Review by MDHayes — CHANGES_REQUESTED** [review]
What is the purpose of a reducers subdirectory inside the state directory?

Also, remember to have prettier installed in your editor and I suggest having it set to autoformat on save.

**Comment by Bhuvneshwar-MB** [comment]
What is the purpose of a reducers subdirectory inside the state directory?
-> We will have all reducers in reducers subdirectory.

Also, remember to have prettier installed in your editor and I suggest having it set to autoformat on save.
-> from now we have installed prettier nd next commit it will fix.

**Comment by MDHayes** [comment]
I think its better to have reducers in the `/state` directory rather than a subdirectory. Especially for this app, its not hugely complex.

**Comment by Bhuvneshwar-MB** [comment]
Sure.

**Comment by Bhuvneshwar-MB** [comment]
Ok. for this app its ok that reducers under state directory but if we have huge application then is it ok to make subdirectory of actions and reducers under state?

**Review by MDHayes — APPROVED** [review]

**Comment by Bhuvneshwar-MB** [comment]
I have resolved the conflict please merge it to AddJam/medicbleep-handwashtimer.

**Pull request merged**
